### ISSUE TITLE
Face Detect API: Image Size always invalid

### ISSUE THREAD

**Issue by martoncsikos** [felixrieseberg/project-oxford#15]
Hello,

Basic face detection always returns an InvalidImageSize error.
Code I'm using:

```
client.face.detect({
    path: '../imagedb/test.jpg',
    returnFaceId: true,
})
.then(response => {
    console.log('The age is: ' + response[0].faceAttributes.age);
    console.log('The gender is: ' + response[0].faceAttributes.gender);
})
.catch(err => console.log(err));
```

Error returned: 
`{ code: 'InvalidImageSize',
  message: 'Image size is too small or too big.' }`

The error is returned regardless of the image size or format, but only when uploading local file. The same image is accepted when used from URL.
I could be missing something obvious here, but can't figure out.
[This thread](http://stackoverflow.com/questions/35294369/projectoxford-emotion-recognition) might be vaguely related.

Thanks,
Marto

**Comment by cthrash** [comment]
This is the same issue as [reported earlier](https://github.com/felixrieseberg/project-oxford/issues/14).  I'll ping the team again about the fix.  Specifying an url continues to work as always.

**Comment by radiofrequency** [comment]
this pull request fixes this issue by avoiding using streams.. thanks for the hint @cthrash 

https://github.com/felixrieseberg/project-oxford/pull/16

**Comment by 4F2E4A2E** [comment]
please add support for blobs.

**Comment by cthrash** [comment]
Please consider upvoting [this](https://cognitive.uservoice.com/forums/356325-apis/suggestions/14858679-support-data-uris-in-image-apis-vision-emotion-fa) if that is the feature you're seeking.

**Comment by 4F2E4A2E** [comment]
First of all, thank you for this lib, it saved me a lot of time, this is a
great lib!

I am not quite sure it is. What the devs need is actually very simple. Once
an image is gathered via canvas from the video / cam feed, one does not
simply blob the image into a tmp folder through expensive filesystem calls
on the server and then pass it on the the oxford-lib, this would make no
sense.

Instead either base64 encoded strings or blobs should be accepted, similar
or exactly like those guys are doing it:
http://stackoverflow.com/questions/34047648/how-to-post-an-image-in-base64-encoding-via-ajax/34064793#34064793

Like that with $.ajax:

$.ajax({
    url: 'https://api.projectoxford.ai/vision/v1/ocr?' + $.param(params),
    type: 'POST',
    processData: false,
    contentType: 'application/octet-stream',
    data: makeblob('data:image/jpeg;base64,9j/4AAQSkZJRgA..........gAooooAKKKKACiiigD//Z'
 }).done(function(data) {alert("success");}).fail(function() {alert("error");});

​Like that with oxford-lib:

client.face.detect({
    data: makeblob('data:image/jpeg;base64,9j/4AAQSkZJRgA..........gAooooAKKKKACiiigD//Z',
    returnFaceId: true,
})
.then(response => {
    console.log('The age is: ' + response[0].faceAttributes.age);
    console.log('The gender is: ' + response[0].faceAttributes.gender);
})
.catch(err => console.log(err));

**Comment by cthrash** [comment]
What's being proposed is simpler still, but requires a change in the server:

```
client.face.detect({
    url: 'data:image/jpeg;base64,9j/4AAQSkZJRgA..........gAooooAKKKKACiiigD//Z',
    returnFaceId: true,
})
.then(...)
```

The thinking is that this would benefit all clients, not just this library.

**Comment by 4F2E4A2E** [comment]
Yes, exactly. The change in the server is only required for the base64
support, how realistic would that be do you think? Should i still vote for
the one mention by you before?
It would be great - if the chances they would change that are poor and i
think they are :) - to have this less <adjective> solution untill then
right? Like:
data:
makeblob('data:image/jpeg;base64,9j/4AAQSkZJRgA..........gAooooAKKKKACiiigD//Z',

**Comment by cthrash** [comment]
Just to follow up, a client change has been made to accept `Buffer` objects _for the Face API_.  A helper method was made on the Oxford object to create a buffer from a Data URI to make this possible:

```
var oxford = require('project-oxford'),
    client = new oxford.Client(process.env.OXFORD_KEY);

client.face.detect({
    data: oxford.makeBuffer('data:image/jpeg;base64,.....', })...
```

Based on the feedback, we can expand this to other APIs.

**Comment by 4F2E4A2E** [comment]
Did work very well with v1.4.0.
Just updated a [gist](https://gist.github.com/4F2E4A2E/6619cb3ed732eee48e040c56f5769732) using the new method together with meteor.
