### ISSUE TITLE
Face Identify API with publicly available Person Groups

### ISSUE THREAD

**Issue by saidimu** [felixrieseberg/project-oxford#18]
According to the [Identify API](https://github.com/felixrieseberg/project-oxford#Client.face..identify), a `personGroupId` must be specified from which faces will be identified. For public figures (celebrities, politicians etc) is there a public set of `personGroupIds` that can be used instead of one having to prepare and train their own person groups?

The idea is to be able to perform face identification such as https://www.captionbot.ai/ does.

**Comment by felixrieseberg** [comment]
Hey! Something like that is sadly not available, so I'm closing this issue for now - but thank you so much for trying it out!

The idea is pretty good, may I suggest that you add it to [UserVoice](https://cognitive.uservoice.com/)?

**Comment by cthrash** [comment]
Hi @saidimu, I've updated the Vision API to expose this functionality.  There's an [example ](https://github.com/felixrieseberg/project-oxford/blob/master/test/test_vision.js#L162) of how you'd use it.
