### ISSUE TITLE
401 Invalid Subscription Key

### ISSUE THREAD

**Issue by sumeetekbote** [felixrieseberg/project-oxford#24]
Hello! 

So I would love to use this library. I have been using face detection through a small client I made in c# but I would like to make a small node app to create smart thumbnails. The only issue is I am having a 401 when trying to use my api key. It works in the api test console but I get this error when trying to use the app:
Unhandled rejection Error: { "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }

index.js:

var oxford = require('project-oxford'),
    client = new oxford.Client('<mykey>');
const fs = require('fs');

    client.vision.thumbnail({
    path: './image.jpg',
    height: 150,
    width: 150,
    smartCropping: true,
    pipe: fs.createWriteStream('./photo2.jpg')
    }); 

Let me know if I am doing something wrong or if you need any information

**Comment by cthrash** [comment]
You need to provide a subscription key in the oxford.Client constructor.
If you don't yet have a subscription key, you can get a free one [here](https://www.microsoft.com/cognitive-services/en-US/subscriptions).
You might find the [test cases](https://github.com/felixrieseberg/project-oxford/blob/master/test/test_face.js) included with this project a good guide on how to use the API.

**Comment by sumeetekbote** [comment]
I am providing my subscription key from azure.  But I am still getting this
error.

**Comment by cthrash** [comment]
That's strange.  What's the URL of the API console you were successful with?

**Comment by sumeetekbote** [comment]
I tried it from the api docs. This is the link: https://dev.projectoxford.ai/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236/console

Just for reference the key I used was when I signed up for the api it gave me two keys and I revealed one and just used that one.

**Comment by cthrash** [comment]
I got it - so the different Microsoft Cognitive Service APIs require independent API keys (one for Face, one for Vision, etc.) as they have different rate-limits and monthly quotas.  You can get a free Vision API key in the aforementioned subscription [page](https://www.microsoft.com/cognitive-services/en-US/subscriptions).

**Comment by sumeetekbote** [comment]
Oh so I need a vision key and not a face key? I will give it a shot.
Thanks!

**Comment by sumeetekbote** [comment]
So that key didn't work either. I have attached an image of both the API keys I have been using. 
<img width="981" alt="screen shot 2016-09-12 at 3 50 37 pm" src="https://cloud.githubusercontent.com/assets/343329/18425922/c71bf5b6-7900-11e6-9556-f9484918a313.png">

**Comment by cthrash** [comment]
I used my old key and it worked, but once I regenerated a key, I got the same error as you.  This suggests something is wrong with the key servers. I will contact the support team to see what's up.

**Comment by cthrash** [comment]
It seems to back again.  Can you try once more?

**Comment by sumeetekbote** [comment]
It seems to be working now! Thanks for your help figuring this out! (even though it seems to have just been an error on their side) Really appreciate it :)

**Comment by cthrash** [comment]
Closing

**Comment by ap185304** [comment]
hiii, i have a doubt.... in my program giving the same error like,invalid key.....once i used free trial,,,then i go for another free trial ..but this time its giving error ,why so....????

**Comment by tahazayed** [comment]
I have changed the URL to "https://westcentralus.api.cognitive.microsoft.com/face/v1.0"

It seems the KEYs are not replicated to all locations

_faceClient = new FaceServiceClient(Properties.Settings.Default.FaceAPIKey, "https://westcentralus.api.cognitive.microsoft.com/face/v1.0");

**Comment by darkknightIr** [comment]
!] FrameworkException: 401: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.
File "/usr/share/recon-ng/recon/core/module.py", line 351, in search_bing_api.
