### ISSUE TITLE
GroupID is invalid

### ISSUE THREAD

**Issue by kdupreez** [felixrieseberg/project-oxford#32]
i tired the following to create a personGroup, but I keep getting an error:
{ code: 'BadArgument', message: 'Person group ID is invalid.' }

This is the code:
var faceclient = new oxford.Client('MY-KEY');

    faceclient.face.personGroup.create({
            personGroupId: 'group1', 
            name: 'testgroup'
    }).then(function(response){

        console.log(response);

    }).catch(function(err){
        console.log(err);
    });

**Comment by cthrash** [comment]
Those are meant to be plain arguments, i.e.:

`faceclient.face.personGroup.create('group1', 'testgroup', '')
`

**Comment by kdupreez** [comment]
Ah.. Thank you!
