### ISSUE TITLE
confidenceThreshold is not supported in face.identify

### ISSUE THREAD

**Issue by bobmoff** [felixrieseberg/project-oxford#36]
According to the API there is the possibility to control the confidenceThreshold

https://dev.projectoxford.ai/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395239

would be nice to have :)

**Comment by bobmoff** [comment]
Hurray!

Hmm, I didnt get any notification of that you have merged this. I guess referencing stuff doesnt trigger notifications.

I guess your waiting for release it to NPM, as you havent closed this issue yet ?

I will npm install directly from github in the meantime. Thx!

**Comment by cthrash** [comment]
1.8 is out today.  Sorry for the delay
