### ISSUE TITLE
client.face.identify ->Request body is invalid

### ISSUE THREAD

**Issue by Stan92** [felixrieseberg/project-oxford#37]
Hi,
I've a little problem using the identify method.

 ```
client.face.identify({
            faces: ["myfaceid"],
            personGroupId:"mygroup",
            maxNumOfCandidatesReturned: 1,
            confidenceThreshold: 1
        }).then(function (response) {
            console.log(response);

        }).catch(function (err) {
            console.log(err);
        });
```

I get this error : 
{ code: 'BadArgument', message: 'Request body is invalid.' }

Do I miss something?
Thanks

**Comment by cthrash** [comment]
`face.identify` takes arguments directly, not an object.  IOW, you'll want:

`client.face.identify([...], "mygroup", 1, 1).then...`

Also Face.Identify takes face ID values as returned by Face.Detect.  They will look like GUIDs.

**Comment by Stan92** [comment]
My mistake.. it works..
For the faceIDs, I use Guid.. 
Thanks.
