### ISSUE TITLE
targetFace format in person.addFace(personGroupId, personId, options) 

### ISSUE THREAD

**Issue by candyaou** [felixrieseberg/project-oxford#40]
Hello i'm beginner in Node.js, i have some question.
I don't understand about the format of targetFace.
i have try 751,549,473,473.
Also, {left:751,top:549,width:473,height473}
And the response is 
code: 'BadArgument', message: 'Invalid argument targetFace.
So, could anybody give me a format of targetFace

Thanks.

**Comment by cthrash** [comment]
If you're referring to the emotion API, you are not required to provide a face rectangle.  You can provide one if you happen to already know where the face rectangle is located, and the API call will take slightly less time.  The [tests](https://github.com/felixrieseberg/project-oxford/blob/master/test/test_emotion.js#L42) have an example of how you would provide a face rectangle.

**Comment by candyaou** [comment]
i work in face API, i have to provide targetFace because in image have more that one face. So, i must provide targetFace to specfic where the face rectangle is located. Refer to test_face.js, it doesn't have example how to provide targetFace like test_emotion.js have.

If i misunderstanding anything please tell me, thanks

**Comment by cthrash** [comment]
Which method are you talking about?  Detect? The face API doesn't take face rectangles as an argument. It will return an array of values, one per face. If you're only interested in one face, you can crop the image before sending it to the API. How do you have the rectangles in the first place?

**Comment by cthrash** [comment]
Sorry - reread the title, and finally understood what you were asking.
This isn't the most optimal implementation, but you need to something like this:
```
client.face.faceList.addFace(..., {targetFace: '751,549,473,473', ...})
```
In other words, the rectangle must be provided in string form.
