### ISSUE TITLE
Accept multiple regions for API endpoint

### ISSUE THREAD

**Issue by hxlnt** [felixrieseberg/project-oxford#42]
Paid Cognitive Services accounts can have endpoint regions outside of `westus`. Can we add an optional param to `Client.face` that allows users to specify an API endpoint region. If no param is passed through, it can default to `westus`.

Ex:
```
Client.face.detect({
   url: 'http://www.myi...jpg',
   region: 'eastus'
});
```

Currently, `oxford.js` hard-codes the `westus` endpoint, which will not work for any paid Cognitive Services accounts outside of the West US region.

I can help refactor the code, but this seemed like too big of a change for a PR without some discussion first.

Tagging @mabast1, who helped uncover this issue!

**Comment by howlowck** [comment]
Hey @hxlnt, I would say for now, you can specify the full endpoint by passing it in as the second parameter when you instantiate the Client.

```js
const { Client } = require('project-oxford')
const apiClient = new Client(apiKey, 'https://westus.api.cognitive.microsoft.com')
```

But I agree, you can't reuse the client object for other services.  The assumption that all the Cognitive Services have the same region is no longer a valid one.  It is better to have the option to specify separate regions for different cog service endpoints.

**Comment by hxlnt** [comment]
@howlowck Yup, definitely! I was hacking with a student today, and we already got a quick fix implemented for his code. Just thought I'd open this up as an issue, as it could be tricky to debug for others. 

In particular, our issue was that he had a Face Group previously trained on `westus`. When migrating to a paid API key on `eastus`, we had to 1) adjust the endpoint for the new key but also 2) re-create/re-train the Face Groups on the new endpoint location, as the IDs were pointing to the wrong location as well.

🎉

**Comment by cthrash** [comment]
Please let me know if the comment [here](https://github.com/felixrieseberg/project-oxford/issues/43#issuecomment-305005684) adequately addresses your requirements.

**Comment by hxlnt** [comment]
Thanks, @cthrash--No requirements on my end, more just a question of whether any refactoring would be helpful given that developers might be working with multiple region endpoints in the same code. (As @howlowck mentions above, Client objects can't be reused in that case.) And/or, it might be helpful just to be more explicit in the README about passing in the endpoint option now that it's more relevant than it was a few months ago. I can take a crack at that.

**Comment by cthrash** [comment]
The `client` isn't generally reusable since the API key is different for each service/region.  The API is structured in such a way that this isn't obvious, I agree.  It is absolutely true that moving forward, the host should not be an optional parameter to the client ctor.  This update was intended to balance the desire to 'fix' things without breaking existing users.  Updates to README is welcome.
