### ISSUE TITLE
401 Invalid Subscription Key #24

### ISSUE THREAD

**Issue by sayaleepote** [felixrieseberg/project-oxford#43]
Getting the same #24 error for FACE API. The subscription key is right.
Even checked the response on this link - [https://dev.projectoxford.ai/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236/console]

The response is -
Access denied due to invalid subscription key. Make sure you are subscribed to an API you are trying to call and provide the right key.

**Comment by cthrash** [comment]
My understanding is that region-neutral API endpoints are retired, and you must now get a key for the given region.  Does your key, for instance, work in the [westus](https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395248) dashboard?

I believe the guidance is to get an Azure-issued key nowadays.  You can get your free Face API key [here](https://azure.microsoft.com/en-us/try/cognitive-services/?api=face-api).  When you do, you are prompted to choose a region.

Please note this nodejs package defaults to **westus** endpoints.  You must override this by providing the appropriate host override in the client constructor [here](https://azure.microsoft.com/en-us/try/cognitive-services/?api=face-api).

**Comment by sayaleepote** [comment]
My key does not work for **westus** dashboard. I do not belong to that region.
But surprisingly this problem is only for face API. The key for emotion API works perfectly.

Can you elaborate on this:

"Please note this nodejs package defaults to westus endpoints. You must override this by providing the appropriate host override in the client constructor here."

The link on the word "here" opens the same link as the link to get the face api key.

**Comment by cthrash** [comment]
It seems I pasted the wrong link.  Here is the [correct link](https://github.com/felixrieseberg/project-oxford/blob/master/src/oxford.js#L30) to the source.

**Comment by sayaleepote** [comment]
Okay thanks. But I believe my country does not fall under any of the regions for which the API is available. Is there any way to get it work?

**Comment by cthrash** [comment]
You should pick the region with the lowest latency.  Typically this will be the region closest geographically.

**Comment by Phumba2** [comment]
hi cthrash,
i also got 2 keys and if i try to use it in the API console, it works on one region which means that my subscription key is valid.  however, if i use the same key in the Cognitive Face Recognition sample provided in github by microsoft (https://github.com/Microsoft/Cognitive-Face-Android) and run it in my phone or emulator choosing the "Detect Face" button, it gives an error "Access denied. Invalid Subscription key".  Why is it that if I use the key in the API testing console it is recognized but not in the sample app.
kind regards,
phumba

**Comment by cthrash** [comment]
Which region is your key for?  The sample app, unless you modify it, will default to using [westus](https://github.com/Microsoft/Cognitive-Face-Android/blob/994f0b360aac19f1cbd94c759f494bb6ce8a0552/ClientLibrary/lib/src/main/java/com/microsoft/projectoxford/face/FaceServiceRestClient.java#L71).

**Comment by hxlnt** [comment]
See https://github.com/felixrieseberg/project-oxford/issues/42 for additional information and guidance for getting non-westus regions working with this module.

**Comment by Phumba2** [comment]
thanks cthrash. in the api console testing console, i used west central US(that is the one that worked).  How do i change the sample android app to then connect to the West central US?

**Comment by cthrash** [comment]
@Phumba2 can you repost your question on _that_ repo, since it's only tangentially relevant here, but potentially relevant to other users of that repo.

Also, are you looking for an answer other than change the default and recompile?

**Comment by Phumba2** [comment]
@cthrash 
Thanks. There is nothing in that repo to post.  It just says that for Support Questions go to StackOverflow and that is why I ended up here having the same issue about 401 with invalid subscription key.
Yes, I am looking for an answer in terms of being able to change the default and compile. I can see the host name when the project oxford is imported from the Maven repository which is westus but I cannot change it since it is in its compiled version and everytime I open the project, it does a build and creates a new classes.jar file with the default host name.  Would appreciate if you can direct me in terms of where or how I can change the host name to point to westcentralus instead of westus.  If I cannot change it at all, if you can advise me in terms of which country should I use when I get a New Trial key so that it works on the WESTUS hostname.  Would appreciate any help/direction from you.  Thanks

**Comment by cthrash** [comment]
I see, you're not building it directly.  Looks to me like [this](https://github.com/Microsoft/Cognitive-Face-Android/issues/15) is basically the tracking issue you're looking for?

The current process for getting API keys is through the Azure Portal.  The link for Computer Vision is [here](https://portal.azure.com/#create/Microsoft.CognitiveServicesComputerVision).  Here you can choose a region in a drop down.

**Comment by Phumba2** [comment]
Thanks @cthrash for the tracking issue link.  i posted my issue there.  I did not go thru the Azure portal as I dont want to put in my credit card details yet and would just want to use the 30 day trial and see how it works and see if I will have a use case for it and also see how good it is.

**Comment by cthrash** [comment]
Just to close this topic, here are what folks need to know regarding API keys:

If you have a 'free trial' API key, please go to the [My API page](https://azure.microsoft.com/en-us/try/cognitive-services/my-apis/) to find out where your endpoint is located (westus, westcentralus, etc.)

If you have a subscription on Azure (note some APIs also have a free tier, but will require an Azure account), please find that item under the [Cognitive Services blade](https://portal.azure.com/#blade/HubsExtension/Resources/resourceType/Microsoft.CognitiveServices%2Faccounts).   The endpoint will listed there.

You can instantiate the `oxford.Client` one of two ways:

```
var oxford = require('project-oxford');
var client = new oxford.Client('your-api-key', oxford.region.WEST_CENTRAL_US);
```
-or-

```
var oxford = require('project-oxford');
var client = new oxford.Client('your-api-key', 'https://westcentralus.api.cognitive.microsoft.com');
```
