### ISSUE TITLE
Using the client.face.verify

### ISSUE THREAD

**Issue by andrehsmendes** [felixrieseberg/project-oxford#47]
Hello,

i'm having difficulty understanding how to use the face.verify feature.

The documentation says that i need an array of STRINGS containing 2 face ids.

But i keep getting the error message: "Faces array must contain two face ids"

My array: 
`faces:['be4c2979-97c7-4b82-801e-093e79cb9dee','b1bee0de-f6ce-40d3-8513-dd3809cb1ae8']`

What am i missing here?

**Comment by cthrash** [comment]
The API takes a simple array of two face strings.  In other words you want:
```
client.face.verify(['be4c2979-97c7-4b82-801e-093e79cb9dee','b1bee0de-f6ce-40d3-8513-dd3809cb1ae8'])
```
It looks like you're passing an object with a field named 'faces'.

**Comment by andrehsmendes** [comment]
Thank you @cthrash 
i don't know how i missed it.
Great work on this repo.
