### ISSUE TITLE
face.verify for face to person verification

### ISSUE THREAD

**Issue by andrehsmendes** [felixrieseberg/project-oxford#49]
Hey,

How to use the face.verify to support face to person verification?

The face API is expecting :
```
{
    "faceId":"c5c24a82-6845-4031-9d5d-978df9175426",
    "personId":"815df99c-598f-4926-930a-a734b3fd651c",
    "personGroupId":"sample_group"
}
```
Reference Page: [Api Doc](https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f3039523a)

**Comment by cthrash** [comment]
I've updated `face.verify` to allow this alternate mode for verification.
If you're consuming this repo, you should be good to go.  If you're consuming the npm package, you'll need to wait for @felixrieseberg  to get around to it.

**Comment by andrehsmendes** [comment]
@cthrash great!
I'm using the npm package, but it is good that it will support it now.

thx
