### ISSUE TITLE
example bug

### ISSUE THREAD

**Issue by AdamGlass** [felixrieseberg/project-oxford#5]
the code in the example doesn't work: 

  console.log('The age is: ' + response.body.attributes.age);
    console.log('The gender is: ' + response.body.attributes.gender);

the response appears to be an array:
[ { faceId: '50b19030-b0f2-4de4-9e21-583a6fbf39f8',
    faceRectangle: { top: 1448, left: 1213, width: 255, height: 255 },
    attributes: {} },
  { faceId: '7558eda3-933c-49fe-8627-2dfd5cd9584e',
    faceRectangle: { top: 1127, left: 2372, width: 180, height: 180 },
    attributes: {} },
  { faceId: 'a727672e-b69f-455f-9a9f-585627ea24ba',
    faceRectangle: { top: 741, left: 1928, width: 71, height: 71 },
    attributes: {} } ]

no body, should index through the array, and i'm not sure what the deal is with no gender info.

(work at microsoft as well)

**Comment by felixrieseberg** [comment]
Thanks for letting me know! That should now be fixed :)

**Comment by yysg** [comment]
May be the response changed after souse api updated,the argument now is like this,
 { faceRectangle: { top: 104, left: 660, width: 203, height: 203 },
    faceAttributes: { gender: 'female', age: 8.5 } ,
so the example face api occur's error.you can fix it when you are free,so that someone new to this can learn better~~~
