### ISSUE TITLE
person.deleteFace promise doesnt resolve to any result

### ISSUE THREAD

**Issue by bobmoff** [felixrieseberg/project-oxford#52]
```javascript
const res = await api.face.person.deleteFace(personGroupId, personId, persistedFaceId)
console.log('removeFaceFromPerson result ->', res)
```

console log prints nada
```javscript
removeFaceFromPerson result ->
```

it is just and empty string, it seems

**Comment by cthrash** [comment]
That's what the [API](https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f3039523e) returns, so that's by design.  What would you rather it return?

**Comment by bobmoff** [comment]
Aha. I understand. I was confused by the comments in the code. I thought it might return some kind of success message.

![image 2017-11-16 at 7 26 56 pm](https://user-images.githubusercontent.com/1033236/32908628-5a1eafb0-cb04-11e7-9ce3-38e82e847b46.png)

**Comment by cthrash** [comment]
Fair point.  I believe that's called cut and past 😄

**Comment by bobmoff** [comment]
Should it be this ?

`A successful call returns an empty response body.`

If there is an error, it wouldnt be as a return value, it would reject the promise, right ?

**Comment by bobmoff** [comment]
or empty string, maybe. :)

**Comment by bobmoff** [comment]
Ah, just found this a tiny bit above, hehe

![image 2017-11-16 at 7 34 50 pm](https://user-images.githubusercontent.com/1033236/32908929-6acbf15a-cb05-11e7-895c-afeeb15cbcc1.png)
